import type { InputType, TranslationItem } from "@/types/translation";
export type SourceItem = Omit<TranslationItem, "translation">;
const WORD = /[A-Za-z]+(?:['’-][A-Za-z]+)*(?:\d+(?:\.\d+)*)?/g;
const SENTENCE = /[^.!?\n]+(?:[.!?]+|$)/g;
export function normalize(text: string) { return text.replace(/\r\n?/g, "\n").trim(); }
export function splitSentences(text: string): SourceItem[] { const matches = Array.from(text.matchAll(SENTENCE)); const sentences = matches.map((match, sentenceIndex) => { const raw = match[0]; const leading = raw.match(/^\s*/)?.[0].length ?? 0; const source = raw.trim(); const start = (match.index ?? 0) + leading; return { source, start, end: start + source.length, sentenceIndex }; }).filter((item) => /[A-Za-z]/.test(item.source)); return sentences.length ? sentences : [{ source: text, start: 0, end: text.length, sentenceIndex: 0 }]; }
export function splitWords(text: string, sentences: SourceItem[]): SourceItem[] { return Array.from(text.matchAll(WORD)).map((match) => { const start = match.index ?? 0; const sentence = sentences.find((item) => start >= item.start && start < item.end) ?? sentences[0]; return { source: match[0], start, end: start + match[0].length, sentenceIndex: sentence.sentenceIndex }; }); }
export function classify(text: string, words: SourceItem[], sentences: SourceItem[]): InputType { if (words.length === 1) return "word"; if (sentences.length >= 2) return "paragraph"; if (/[.!?]$/.test(text) || words.length > 8) return "sentence"; return "phrase"; }
export function validatePhrases(text: string, phrases: Array<{ source: string; start: number; end: number }>, sentences: SourceItem[]) { return phrases.filter((phrase) => phrase.start >= 0 && phrase.end <= text.length && phrase.end > phrase.start && text.slice(phrase.start, phrase.end) === phrase.source).filter((phrase) => (phrase.source.match(WORD) ?? []).length >= 2 && (phrase.source.match(WORD) ?? []).length <= 8).map((phrase) => ({ ...phrase, sentenceIndex: (sentences.find((item) => phrase.start >= item.start && phrase.start < item.end) ?? sentences[0]).sentenceIndex })).sort((a, b) => a.start - b.start || a.end - b.end); }
